switch:
    ## Calibration and Optimization cost analysis
    kCeresOpt: true
    kMultiSpotsOpt: false
    kParamsAnalysis: false
    kUniformSampling: false
    kCamMode: 0 # 0 = omni camera; 1 = pinhole camera

essential:
    kLidarTopic: "/livox/lidar"
    kNumSpot: 1 # -1: means run all the spots, other means run the specific spot index
    kDatasetName: "sustech_crf" # "sustech_rb1" "sustech_bs_hall" "LL"
    kImageRows: 2048
    kImageCols: 2448
    kFlatRows: 2000
    kFlatCols: 4000
    bw: [32.00, 16.00, 8.00, 4.00, 2.00]

extrinsic:
    # initial extrinsic parameters
    # euler angles follow: R = Rx * Ry * Rz
    rx: 3.1415926   # pi/2
    ry: 0.01        # 0
    rz: 1.5707963  # pi/2
    tx: 0.27        # 0.0
    ty: 0.00        # 0.06
    tz: 0.03        # -0.03
    # range
    rx_range: 0.10
    ry_range: 0.10
    rz_range: 0.10
    tx_range: 0.10
    ty_range: 0.10
    tz_range: 0.10
    
intrinsic_omni:
    # omnidirectional camera initial intrinsic params
    u0: 1023.00
    v0: 1201.00
    a0: 1937.487404 # 616.7214056132 * M_PI
    a1: -616.7214056132
    a2: 0.00
    a3: 0.00
    a4: 0.00
    c: 1.00
    d: 0.00
    e: 0.00
    # range
    u0_range: 50.00
    v0_range: 50.00
    a0_range: 200.00
    a1_range: 100.00
    a2_range: 100.00
    a3_range: 50.00
    a4_range: 10.00
    c_range: 0.01
    d_range: 0.01
    e_range: 0.01

intrinsic_pinhole:
    # pinhole camera initial intrinsic params
    fx: 2571.0
    fy: 2571.0
    cx: 1172.0
    cy: 1013.0
    k1: -0.148
    k2: 0.123
    p1: 0.0
    p2: 0.0
    # range
    fx_range: 50.0
    fy_range: 50.0
    cx_range: 50.0
    cy_range: 50.0
    k1_range: 0.5
    k2_range: 0.5
    p1_range: 1.0
    p2_range: 1.0
    
    
    
